#!/bin/bash

# ---- Configurable Variables ----
KEY_FILE="key.pem"  # Path to your SSH key
PUBLIC_IP="3.149.25.230"
PRIVATE_IP_INT_SVC="10.0.0.91"
USER="core"
REMOTE_PATH="/var/home/core"
LOCAL_KUBECONFIG_PATH="/tmp/kubeconfig"
KUBECONFIG_REMOTE="$REMOTE_PATH/kubeconfig"
SCRIPT_NAME="generate_external_frr.sh"

cat << 'FRR_SCRIPT' > $SCRIPT_NAME
#!/bin/bash
set -o nounset
set -o errexit
set -o pipefail


generate_frr_config() {
    local NODE="$1"  # Get NODE argument
    local OUTPUT_FILE="$2"  # Get output file path argument
    local IFS=' '
    read -ra ips <<< "$NODE"
    local ipv4_list=()
    
    # First filter out IPv4 addresses
    for ip in "${ips[@]}"; do
        if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            ipv4_list+=("$ip")
        fi
    done

    # Write to file using heredoc
    cat > "$OUTPUT_FILE" << EOF
router bgp 64512
 no bgp default ipv4-unicast
 no bgp network import-check

EOF

    # Generate neighbor remote-as section
    for ip in "${ipv4_list[@]}"; do
        echo " neighbor $ip remote-as 64512" >> "$OUTPUT_FILE"
    done
    echo "" >> "$OUTPUT_FILE"

    echo " address-family ipv4 unicast" >> "$OUTPUT_FILE"
    echo "  network 172.20.100.0/24" >> "$OUTPUT_FILE"
    for ip in "${ipv4_list[@]}"; do
        echo "  neighbor $ip activate" >> "$OUTPUT_FILE"
        echo "  neighbor $ip next-hop-self" >> "$OUTPUT_FILE"
        echo "  neighbor $ip route-reflector-client" >> "$OUTPUT_FILE"
    done
    echo " exit-address-family" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"

}
generate_daemons() {
local FILE_NAME="$1"
cat > "$FILE_NAME" << EOF
# This file tells the frr package which daemons to start.
#
# Sample configurations for these daemons can be found in
# /usr/share/doc/frr/examples/.
#
# ATTENTION:
#
# When activating a daemon for the first time, a config file, even if it is
# empty, has to be present *and* be owned by the user and group "frr", else
# the daemon will not be started by /etc/init.d/frr. The permissions should
# be u=rw,g=r,o=.
# When using "vtysh" such a config file is also needed. It should be owned by
# group "frrvty" and set to ug=rw,o= though. Check /etc/pam.d/frr, too.
#
# The watchfrr and zebra daemons are always started.
#
bgpd=yes
ospfd=no
ospf6d=no
ripd=no
ripngd=no
isisd=no
pimd=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
bfdd=yes
fabricd=no
vrrpd=no

#
# If this option is set the /etc/init.d/frr script automatically loads
# the config via "vtysh -b" when the servers are started.
# Check /etc/pam.d/frr if you intend to use "vtysh"!
#
vtysh_enable=yes
zebra_options="  -A 127.0.0.1 -s 90000000"
bgpd_options="   -A 127.0.0.1"
ospfd_options="  -A 127.0.0.1"
ospf6d_options=" -A ::1"
ripd_options="   -A 127.0.0.1"
ripngd_options=" -A ::1"
isisd_options="  -A 127.0.0.1"
pimd_options="   -A 127.0.0.1"
ldpd_options="   -A 127.0.0.1"
nhrpd_options="  -A 127.0.0.1"
eigrpd_options=" -A 127.0.0.1"
babeld_options=" -A 127.0.0.1"
sharpd_options=" -A 127.0.0.1"
pbrd_options="   -A 127.0.0.1"
staticd_options="-A 127.0.0.1"
bfdd_options="   -A 127.0.0.1"
fabricd_options="-A 127.0.0.1"
vrrpd_options="  -A 127.0.0.1"

# configuration profile
#
#frr_profile="traditional"
#frr_profile="datacenter"

#
# This is the maximum number of FD's that will be available.
# Upon startup this is read by the control files and ulimit
# is called. Uncomment and use a reasonable value for your
# setup if you are expecting a large number of peers in
# say BGP.
#MAX_FDS=1024

# The list of daemons to watch is automatically generated by the init script.
#watchfrr_options=""

# for debugging purposes, you can specify a "wrap" command to start instead
# of starting the daemon directly, e.g. to use valgrind on ospfd:
#   ospfd_wrap="/usr/bin/valgrind"
# or you can use "all_wrap" for all daemons, e.g. to use perf record:
#   all_wrap="/usr/bin/perf record --call-graph -"
# the normal daemon command is added to this at the end.

EOF
}


  
  export KUBECONFIG=/var/home/core/kubeconfig
  ip addr add 172.20.100.1/24 dev eth1
  oc patch Network.operator.openshift.io cluster --type=merge -p='{"spec":{"additionalRoutingCapabilities": {"providers": ["FRR"]}, "defaultNetwork":{"ovnKubernetesConfig":{"routeAdvertisements":"Enabled"}}}}'
  NODES=$(kubectl get nodes -o jsonpath={.items[*].status.addresses[?\(@.type==\"InternalIP\"\)].address})
  echo $NODES
  rm -rf /root/frr-ext
  mkdir /root/frr-ext
  cd /root/frr-ext
  generate_daemons /root/frr-ext/daemons
  generate_frr_config "$NODES" /root/frr-ext/frr.conf
  
  sudo podman run -d --privileged --network host --rm --ulimit core=-1 --name frr --volume /root/frr-ext:/etc/frr quay.io/frrouting/frr:9.1.2

FRR_SCRIPT

# ---- Step 1: SCP kubeconfig and script ----
echo "Copying kubeconfig and script to remote host..."
scp -i "$KEY_FILE" -o StrictHostKeyChecking=no $LOCAL_KUBECONFIG_PATH "$SCRIPT_NAME" "$USER@$PUBLIC_IP:$REMOTE_PATH"

# ---- Step 2: Set KUBECONFIG and run the script remotely ----
echo "Running script on remote host..."
ssh -i "$KEY_FILE" -o StrictHostKeyChecking=no "$USER@$PUBLIC_IP" << EOF
  export KUBECONFIG="$KUBECONFIG_REMOTE"
  sudo chmod +x "$REMOTE_PATH/$SCRIPT_NAME"
  sudo "$REMOTE_PATH/$SCRIPT_NAME"
EOF

# 
oc apply -f - <<EOF
apiVersion: frrk8s.metallb.io/v1beta1
kind: FRRConfiguration
metadata:
  name: receive-all
  namespace: openshift-frr-k8s
spec:
  bgp:
    routers:
    - asn: 64512
      neighbors:
      - address: ${PRIVATE_IP_INT_SVC}
        disableMP: true
        asn: 64512
        toReceive:
          allowed:
            mode: all
EOF
